SELECT DISTINCT T1.CART_ID
FROM CART_PRODUCTS T1
JOIN CART_PRODUCTS T2
ON T1.CART_ID = T2.CART_ID
WHERE (T1.NAME = 'Yogurt' AND T2.NAME = 'Milk') OR (T1.NAME = 'Milk' AND T2.NAME = 'Yogurt')
ORDER BY T1.CART_ID;