SELECT INS.ANIMAL_ID,
       INS.ANIMAL_TYPE,
       INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE NOT IN ('Spayed Female','Neutered Male') AND
OUTS.SEX_UPON_OUTCOME IN ('Spayed Female','Neutered Male')
ORDER BY INS.ANIMAL_ID;
