WITH RECURSIVE TIME AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM TIME
    WHERE HOUR < 23
), ANIMAL AS(
    SELECT HOUR(DATETIME) HOUR,
           COUNT(ANIMAL_ID) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)

SELECT T.HOUR,
       CASE
            WHEN A.COUNT IS NULL THEN 0 ELSE A.COUNT
       END COUNT
FROM TIME T
LEFT JOIN ANIMAL A
ON T.HOUR = A.HOUR
ORDER BY T.HOUR;