SELECT MEMBER.MEMBER_NAME,
       REST.REVIEW_TEXT,
       DATE_FORMAT(REST.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE MEMBER
JOIN REST_REVIEW REST
ON MEMBER.MEMBER_ID = REST.MEMBER_ID
WHERE MEMBER.MEMBER_ID = (SELECT MEMBER_ID
                          FROM REST_REVIEW
                          GROUP BY MEMBER_ID
                          ORDER BY COUNT(MEMBER_ID) DESC
                          LIMIT 1)
ORDER BY REST.REVIEW_DATE ASC, REST.REVIEW_TEXT ASC;